### ISSUE TITLE
Handling of MultiQC timestamps

### ISSUE THREAD

**Issue by ohofmann** [ewels/MegaQC#61] opened 2018-06-08 03:32 UTC
Following up on our discussion in Stockholm: I'd love to see a slightly different handling of MultiQC timestamps during the import. We'd love to import historical data which is tricky right now as MegaQC associated imported data with the time of when the MultiQC report was generated -- not when the sample was actually run / processed. 

This is also problematic for current data. We frequently sequence data, but then do not analyse it for 2-3 months until all samples of a cohort are available. QC data generated and visualized in MegaQC then appear out of sync with when they were created.

Allowing for a 'timestamp' to be submitted during import would allow us to work around this issue and provide a relatively quick fix.

Long term, a better solution would be to associate timestamps with _samples_ (not MultiQC reports) in the backend database, and to allow users to submit sample name : timestamp mappings in the same way that MultiQC allows for samples to be batch re-labelled. 

Sorry for taking so long to follow up on this ;-)

**Comment by ewels** [comment] 2018-06-13 09:39
Hi @ohofmann,

Yes, I think this would be a good addition. Until fairly recently, sample timestamps were the date of upload which was pretty hopeless - this is now fixed at least and uses the time that the MultiQC report was generated. Still - having an override parameter for the `megaqc upload` command would be an easy addition.

> Long term, a better solution would be to associate timestamps with samples (not MultiQC reports) in the backend database, and to allow users to submit sample name : timestamp mappings in the same way that MultiQC allows for samples to be batch re-labelled.

Sure - I'm expecting several of these cases where we'll want to add in metadata to MultiQC which is only used by MegaQC. This one isn't super simple as MegaQC only stores timestamps on report level currently, but isn't impossible.

Phil

**Comment by skanwal** [comment] 2019-03-15 04:02
Hi Phil,

Following up on this discussion, did you have a chance to think about/implement the `override` parameter for sample timestamps?

Any plan/timeline/thoughts on this?

PS: I acknowledge your highly busy schedule and other things that might be of higher priority - but any feedback on this issue will be appreciated.

Regards,
Sehrish

**Comment by ewels** [comment] 2019-03-15 22:16
Hi Sehrish,

I haven't had any time to work on MegaQC yet I'm afraid, and I will be going on paternity leave soon so I can't promise anything for a while now. But when I'm back at work after the summer I hope to be able to work on MegaQC again. This will be one of my first priorities.

Phil

**Comment by ohofmann** [comment] 2019-03-16 01:13
First, congrats! Second, no worries :) We can have a look at the codebase to explore a PR for this to make your life easier (unless you had a specific place in mind).

**Comment by ewels** [comment] 2019-03-16 16:06
A PR would be great! I was thinking of adding a command line flag for `megaqc upload` (`--date`?). So a `@click.option` here:
https://github.com/ewels/MegaQC/blob/42f7718f7a819acb496d9a74eb020badf7969eda/megaqc/commands.py#L155-L157

You then need to tie in to the code below and modify the JSON object _before_ it's sent off to the `multiqc_api_post` function:

https://github.com/ewels/MegaQC/blob/42f7718f7a819acb496d9a74eb020badf7969eda/megaqc/commands.py#L187-L196

Having a very quick look at this [MultiQC code](https://github.com/ewels/MultiQC/blob/e0cbe2b6b9ed3c5c128bc5c110da0ab0f9da6dc7/multiqc/utils/megaqc.py#L38), I think it's probably `config['creation_date']` that you want to overwrite. That's normally generated [here](https://github.com/ewels/MultiQC/blob/85e92dc1cff8d7682780f4b079113b8350950d0f/multiqc/utils/config.py#L56) (so this is the format that you need to end up generating from whatever was given on the command line):

```python
creation_date = datetime.now().strftime("%Y-%m-%d, %H:%M")
```

Yup, this is where it's later used:
https://github.com/ewels/MegaQC/blob/d2b3634282c9f35c7adf40df267e9afd8054105c/megaqc/api/utils.py#L77-L81

(`config_creation_date` instead of `config['creation_date']` because the multi-dimensional arrays are flattened for storing in the database)

Hope this makes sense! Not too tricky, just needs implementing and testing.

Potentially tricky things to think about:

* Needs to handle whatever random stuff / formats people try to provide on the command line 😅 
  * Different formats, different levels of detail, nice error handling
* Needs to work when multiple JSON files are supplied in one go
* Needs testing to make sure that it definitely has the intended effect
* Needs documentation (cli and docs)

Phil

**Comment by skanwal** [comment] 2019-03-17 21:21
Phil,

Congratulations and thanks a lot for the detailed pointers. 
We'll explore the codebase to implement/test these and will let you know if there are any ambiguities/questions.

All the best.

Regards,
Sehrish

**Comment by TMiguelT** [comment] 2019-05-01 08:03
This would certainly be a useful feature. Has anyone got around to implementing it?

Having said that, an easy workaround for this would be editing the `config_creation_date` field within the `multiqc_data.json`, correct? So this is hardly a critical issue

**Comment by TMiguelT** [comment] 2019-05-01 08:04
My concern is moreso that, if you *ran* multiQC on multiple files that were actually from different dates, there is no way to separate them, because they're now all in the same report file. And each report can only have one date.

**Comment by tsnowlan** [comment] 2019-05-01 10:36
A workaround for multiple samples is to run MultiQC singly for the purposes of sending the data to MegaQC, then running MultiQC on the whole cohort (with MegaQC upload to prevent duplication) once it is ready.

**Comment by TMiguelT** [comment] 2019-05-01 10:38
Do you mean *without* MegaQC upload the second time? But yes I agree this would work.

**Comment by tsnowlan** [comment] 2019-05-01 10:46
Sorry, yes. I'm always leaving out the most important words.

That's how we're currently doing it: nextflow step in the individual pipeline to run MultiQC on a single sample. Then once a batch is finished can do the combined one manually. That way we can still know as it is happening if quality starts dropping.

**Comment by TMiguelT** [comment] 2019-05-27 05:51
Just about to open a PR to fix this. But out of interest, does it make sense for this flag to just set the date, or should we have something that can patch any arbitrary field? e.g. 
```bash
megaqc upload report.json --patch config_creation_date=1970-01-01 --patch 'config_report_comment=This sample sucks'
```

Or am I getting carried away with flexibility at the expense of usability...?

**Comment by skanwal** [comment] 2019-05-27 06:03
Michael,

A quick question - how would `patch` work when uploading multiple `.json` files? 
Or this would apply to when uploading single multiqc report at a time?

**Comment by TMiguelT** [comment] 2019-05-27 06:05
It would have to patch all json files with the same value. So if you needed different behaviour per-file, you'd have to upload them with separate commands. The same would be true for the `--date` field being proposed.

**Comment by TMiguelT** [comment] 2019-05-27 06:06
Because of course you could always do this with JQ at that point:

```
megaqc upload <(jq report.json '.config_creation_date=1970-01-01, .config_report_comment="This sample sucks"')
```

**Closed** 2019-05-27 10:50 UTC
Labels: core: back end

**Comment by ewels** [comment] 2019-05-27 10:56
I love the idea of `--patch`! Could also supply a config file, in case people always want to overwrite the same stuff / more reproducible hacking.

I don't see any reason not to do this, it shouldn't interfere with any existing usability 👍

**Comment by TMiguelT** [comment] 2019-05-27 10:58
Ah, but you just merged my date implementation. If you like the idea of `--patch`, wouldn't patching dates be a subset of this, rather than its own flag?

**Comment by ewels** [comment] 2019-05-27 10:59
I think it makes sense to have both, even though date is a subset. I imagine that 90% of people will want to only patch the date (it's the most-requested feature I think, though low sample size), so makes sense to make this bit as user friendly as possible..
