### ISSUE TITLE
SQL: use a temporary table for sample filters

### ISSUE THREAD

**Issue by ewels** [ewels/MegaQC#70] opened 2018-10-10 15:14 UTC
As data volumes rise, we start to get errors like this:

```
OperationalError: (sqlite3.OperationalError) too many SQL variables [SQL: u'SELECT sample.sample_name AS sample_sample_name \nFROM sample \nWHERE sample.sample_id IN (?, ?,
```
with the `?,` list going on for a long long time.

Instead of building these huge queries which break the SQL engine, we should use a better approach. We could either chunk the queries or [use a temporary table](https://stackoverflow.com/a/5803526/713980) and join. It sounds like the [latter scales better](https://explainextended.com/2009/08/18/passing-parameters-in-mysql-in-list-vs-temporary-table/) performance wise.

Whilst we could use this filter lookup table and save the ID lists, it could get _very_ large. So instead I think it makes sense to fill it temporarily for each call and then empty it. Need to consider race conditions though - so maybe create a random identifier for the filter call so that multiple can happen simultaneously.

@tsnowlan - have you come across this problem yet? Any thoughts on the above?

**Comment by TMiguelT** [comment] 2019-07-04 02:22
I had a look at the root cause of this, and it seems to be a hard (compile-time) limit that SQLite has: https://www.sqlite.org/limits.html. I believe `SQLITE_MAX_VARIABLE_NUMBER` is the relevant variable here, and it apparently defaults to 999, so I'm guessing this error will pop up once the number of samples in the database gets above 999.

**Comment by TMiguelT** [comment] 2019-07-23 10:30
By the way, is this issue a duplicate of #48?

**Closed** 2020-10-06 08:17 UTC
Labels: bug, high priority
